### ISSUE TITLE
are we using Advance Java concept, Node js ??

### ISSUE THREAD

**Issue by zaid-kamil** [aryanpodium777/movie-trends-be#6]
because we dont use this syntax, its basically obslete. and UI wala logic kya h

**Comment by aryanpodium777** [comment]
No JAVA or Node language used here. We are simply creating REST ful webservice (API) using python language.
Flow  of BE calls are Controller(route)->Service->DAO.
UI has been built on Angular framework.
From UI we will be invoking API endpoints to serve its purpose. BE will return response in form of JSON, which will be handled by UI for further actions.

**Comment by zaid-kamil** [comment]
yes, that i this, but this is not python convention to make such a fuss . with classes. and service creation is way easier than this.
